services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: ["/bin/sh", "-c", "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application"]
    working_dir: /code/app
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
      - neo4j
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  neo4j:
    image: neo4j:5
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
